project:
  type: website

website:
  title: "Class"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  
publish:
  github:
    repo: apd217/PSCH543
    branch: gh-pages

